# traefik.yml

api:
  dashboard: true
  insecure: false
  debug: false

ping: {}

log:
  filePath: "/var/log/traefik.log"

accessLog:
  filePath: "/var/log/access.log"
  bufferingSize: 100

providers:
  docker:
    network: proxy
  file:
    directory: /etc/traefik/confs

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: {{DEFAULTEMAIL}}
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: http
