version: '3.7'

networks:
  proxy:
    external: true

services:
  proxy:
    container_name: proxy
    image: traefik:v2.2
    restart: always
    env_file:
      - ../.env
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      # - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
      - ./confs:/etc/traefik/confs
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./.wpenvusers:/etc/traefik/.wpenvusers
    networks:
      - proxy
