# traefik.yml

api:
  # Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard: true
  insecure: false
  debug: false

ping: {}

log:
  filePath: "/var/log/traefik.log"

accessLog:
  filePath: "/var/log/access.log"
  bufferingSize: 100

providers:
  docker:
    network: proxy
  file:
    directory: /etc/traefik/confs

entryPoints:
  http:
    address: ":80"
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
  https:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: ssl@wpenvbox.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: http
